service: PictureSender

frameworkVersion: '3'

provider: 
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  environment:
    TABLE_NAME:
      Ref: UserTable


functions:
  Api:
    handler: src/express_api.handler
    events: 
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  Sender:
    handler: src/sender.handler
    events:
      - schedule: cron(0 4/12 * * ? *)

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PicSenderUserTable
        AttributeDefinitions:
          - AttributeName: Phone
            AttributeType: S
        KeySchema:
          - AttributeName: Phone
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1