
name: deploy zip to lambda
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./backend
jobs:
  deploy_backend:
    name: deploy serverless backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node ./node_modules/serverless/bin/serverless.js config credentials --provider aws --key ${{ secrets.AWS_AKEY_ID }} --secret ${{ secrets.AWS_AKEY_KEY }}
      - run: node ../../node_modules/serverless/bin/serverless.js deploy --stage prod --verbose
        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.secrets.AWS_AKEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secrets.AWS_AKEY_KEY }}
          SLS_DEBUG: 1
